# When the master branch is updated (i.e. a PR is completed)
# Also update the release area

trigger:
  - master

stages:
  - stage: 'all'
    jobs:
    - job: 'CI_no_license'
      pool:
        name: CI_no_license
      steps:
      # Print the pwd to make it easier to find the area where this was run
      - script: |
          pwd
        displayName: 'Display PWD'

      - script: |
          cd /data/tools/EDA
          git pull
        displayName: 'Update release area'
