#!/bin/bash

# --------------------------------------------------
# Script will provide options for inclusion of various EDA Software Resources
#
# Options will be based on Role
# 1. AMS 
# 2. AMS/Photonics 
# 3. AMS/PD 
# 4. RTL/DV 
# --------------------------------------------------

# --------------------------------------------------
# REAX to Command Line Options
# --------------------------------------------------

while (( $# ))
do
    case $1 in
        "--help" | "-h" )
            echo "  Usage Guide for Lightelligence EDA Configurator"
            echo "  usage: edaSetup [-h [--help] -co [--configOption] ROLE"
            echo ""
            echo "  Command Line Options:"
            echo ""
            echo "  -c [--configOption] ROLE       Select your Role, if not provided, interactive selection is enabled"
            echo ""
            echo "                                  Available Roles and Valid Options:"
            echo "                                  1  :: AMS - IC618"
            echo "                                  2  :: AMS - ICADVM181"
            echo "                                  3  :: AMS - ICADVM181/Photonics"
            echo "                                  4  :: AMS - ICADVM181/PD"
            echo "                                  5  :: AMS - ICADVM181/PD-Siph"
            echo "                                  6  :: RTL/DV"
            echo "                                  7  :: Allegro"
            echo ""
            echo " -h [--help]                      Prints help message and exits"
            echo ""
            return
            ;;
        "--configOption" | "-c" )
            # Get Value after -c || --configOption
            shift
            configOption="$@"
            ;;
        *)
            echo $arg
            echo "Unexecpted Command Line Input - Exiting"
            return
            ;;    
    esac
    shift
done

# --------------------------------------------------
# Parse User Input if Command Line Option not Supplied
# --------------------------------------------------

if [ -z "$configOption" ]
then
    echo ""
    echo "  Welcome to the Lightelligence EDA Configurator"
    echo ""
    echo "  Please Select Your Role:"
    echo "  1. AMS - IC618"
    echo "  2. AMS - ICADVM181"
    echo "  3. AMS - ICADVM181/Photonics"
    echo "  4. AMS - ICADVM181/PD"
    echo "  5. AMS - ICADVM181/PD-Siph"    
    echo "  6. RTL/DV"
    echo "  7. Allegro"
    echo -n "  Selection [Press Enter]: "
    read configOption
fi

echo $configOption

# --------------------------------------------------
# **************************************************
#
#            Cadence - AMS ENV Variables
#
# **************************************************
# --------------------------------------------------

configure_CDS_AMS_ENV_VARS() {

    export CDS_LIC_FILE=$LM_LICENSE_FILE
    export CDS_AUTO_64BIT=ALL
    #export SPECTRE_DEFAULTS=-E
    export CDS_Netlisting_Mode=Analog

    export QRC_ENABLE_EXTRACTION=t
    export RCXTODFII_TYPE=QRC

    export CDS_LOAD_ENV=addCWD
    export CDS_LOG_PATH=.
    export CDS_DEFAULT_BROWSER=firefox

    export CDS_ERRORLOG="DIR=/tools/crashlogs"

}

# --------------------------------------------------
# **************************************************
#
#            Cadence - Photonics ENV Variables
#
# **************************************************
# --------------------------------------------------

configure_CDS_SiPh_ENV_VARS() {

    export Virtuoso_Photonics_Option=1
    export Virtuoso_MultiTech=1

}

# --------------------------------------------------
# **************************************************
#
#                       ICManage
#
# **************************************************
# --------------------------------------------------

configure_ICM() {

    #To be placed one level up from the root client directory
    #e.g. if client installed in /eda/icmanage/gdpxl
    #     gdpxl.baschrc file sits in /eda/icmanage

    # --------------------------------------------------
    # ZSH Hack
    # ICManage Requires Bash Complete
    # --------------------------------------------------

    if [ -n "$ZSH_VERSION" ]; then
        # >>> ZSH EDA initialize >>>
        # Source EDA Environment
        #
        autoload bashcompinit   # Need for ZSH Auto-Completion
        bashcompinit            # Need for ZSH Auto-Completion
        # <<< ZSH EDA initialize <<<
    fi

    # Set HOME and PATH Variables
    export ICM_HOME="$TOOLSBASE/icmanage"
    export PATH="$ICM_HOME/gdpxl/bin.lnx86-64:$ICM_HOME/gdpxl/gdm.lnx86-64:$PATH"

    # Set ENV Variables
    export ICM_GDP_SERVER="http://Mach2.lt.lab:5000"
    export ICM_PLASTIC_SERVER="Mach2.lt.lab:8087"
    export PYTHONPATH="$ICM_HOME/gdpxl/cli:$ICM_HOME/gdpxl/pypackages"
    export ICM_SkillRoot="$ICM_HOME/gdpxl"
    export CDS_GDM_SHLIB_LOCATION="$ICM_HOME/gdpxl/gdm.lnx86-64"

    # Source ICM Collateral
    source "$ICM_HOME/gdpxl/cli/noglob"
    source "$ICM_HOME/gdpxl/cli/bash-completion"

}


# --------------------------------------------------
# Tools Base Installation Folder
# --------------------------------------------------

if [ -d "/eda" ]; then
    export TOOLSBASE=/eda
else
    export TOOLSBASE=/tools
fi

# --------------------------------------------------
# Cadence Installation Path
# --------------------------------------------------

export CDSTOOLS=$TOOLSBASE/cadence

# --------------------------------------------------
# EDA Roles and Tool Selection
# --------------------------------------------------

case $configOption in
    1) # AMS - IC618

        # IC Installation
        module load cds/IC618ISR5
        # Simulation
        module load mmsim/191ISR2
        module load xcelium/1809
        # Physical Verification
        module load quantus/191
        module load pvs/161

        configure_CDS
        configure_CDS_AMS_ENV_VARS
        configure_ICM

        ;;
    2) # AMS - ICADVM181
        
        # IC Installation
        module load cds/181
        # Simulation
        module load mmsim/191ISR2
        module load xcelium/1809
        # Physical Verification
        module load quantus/191
        module load pvs/161

        configure_CDS
        configure_CDS_AMS_ENV_VARS
        configure_ICM

        ;;
    3) # AMS - ICADVM181/Photonics
        # IC Installation
        module load cds/181
        # Simulation
        module load mmsim/191ISR2
        module load xcelium/1809
        # Physical Verification
        module load quantus/191
        module load pvs/161

        configure_CDS
        configure_CDS_AMS_ENV_VARS
        configure_CDS_SiPh_ENV_VARS
        module load lumerical
        configure_ICM

        ;;
    4) # AMS - ICADVM181/PD

        # IC Installation
        module load cds/181
        # Simulation
        module load mmsim/181
        module load xcelium/1809
        # Physical Verification
        #module load quantus/191
	module load quantus/201
#        module load pvs/161
	module load pvs/191ISR1

        # Digital Flow
        # module load genus/191
        #module load innovus/181
        #module load innovus/191
        #module load confrml/182
        #module load jls/181
        #module load modus/181
        module load ssv/191ISR2

        configure_CDS
        configure_CDS_AMS_ENV_VARS
        configure_ICM

        ;;
    5) # AMS - ICADVM181/PD

        # IC Installation
        module load cds/181
        # Simulation
        module load mmsim/191ISR2
        module load xcelium/1809
        # Physical Verification
#        module load quantus/191
	module load quantus/201
#       module load pvs/161
	module load pvs/191ISR1

        # Digital Flow
        #module load genus/191
        #module load innovus/181
        module load innovus/191
        #module load confrml/182
        #module load jls/181
        #module load modus/181
        module load ssv/191ISR2

        configure_CDS
        configure_CDS_AMS_ENV_VARS
        configure_CDS_SiPh_ENV_VARS
        module load lumerical
        configure_ICM

        ;;
    6) # RTL/DV
        module load xcelium/1809

        configure_CDS
        ;;
    7) # Allegro
        module load allegro
        module load sigrity

        configure_CDS
        ;;
    *)
        ;;
esac
   
