###############################################################################
# Edit this section

{% set name = "cds_ic" %}
{% set version = "1.0" %}

###############################################################################
# You don't need to edit anything below here

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: env.sh

build:
  number: 0
  script: "mkdir -p $PREFIX/etc/conda/activate.d; cp $RECIPE_DIR/env.sh $PREFIX/etc/conda/activate.d/{{ name | lower}}_activate.sh"
