TOOLS_INSTALL=/tools
CADENCE_DIR=$TOOLS_INSTALL/cadence
export GENUS_VER=191
export PATH=$CADENCE_DIR/GENUS$GENUS_VER/tools.lnx86/bin/64bit:$PATH
export PATH=$CADENCE_DIR/GENUS$GENUS_VER/tools.lnx86/bin:$PATH

