TOOLS_INSTALL=/tools
CADENCE_DIR=$TOOLS_INSTALL/cadence
export XCELIUM_VER=1809
export PATH=$CADENCE_DIR/XCELIUM$XCELIUM_VER/tools.lnx86/bin/64bit:$PATH
export PATH=$CADENCE_DIR/XCELIUM$XCELIUM_VER/tools.lnx86/bin:$PATH
