if [ -d "/eda" ]; then
    export TOOLS_INSTALL=/eda
else
    export TOOLS_INSTALL=/tools
fi

CADENCE_DIR=$TOOLS_INSTALL/cadence
CONFRML_VER=182
CONFRML_HOME=$CADENCE_DIR/CONFRML$CONFRML_VER
export PATH=$CONFRML_HOME/tools/bin:$CONFRML_HOME/tools/dfII/bin:$PATH; 
export CDNSHELP_DOC=$CONFRML_HOME/doc:$CDNSHELP_DOC;
