TOOLS_INSTALL=/tools
CADENCE_DIR=$TOOLS_INSTALL/cadence
export INNOVUS_VER=191
export PATH=$CADENCE_DIR/INNOVUS$INNOVUS_VER/tools.lnx86/bin/:$PATH
export PATH=$CADENCE_DIR/INNOVUS$INNOVUS_VER/tools.lnx86/bin/64bit:$PATH
